### ISSUE TITLE
Vertical Manifold

### ISSUE THREAD

**Issue by sidnigam** [pbnh/unh-aquaponics#12]
Created 3 stls -- 1 for the outlet (simple cylinder), 1 for the box with a cylindrical hole, 1 for the vertical manifold.

copy pasted them into 1 stl, and snappy compiles but mesh isn't right - it's hollow and doesn't have the vertical manifold cylinder with holes

**Comment by petebachant** [comment]
Judging by the [STL rendering on GitHub](https://github.com/pbnh/unh-aquaponics/blob/sidmanifold/constant/triSurface/water.stl), it looks like the outlet face of the manifold (inside the box), might be a "solid" circular surface.

**Comment by sidnigam** [comment]
better now with the outlet and inlet, but I suspect the small cylinders (supposed to be holes) might be too small for the mesh to work properly?

**Comment by sidnigam** [comment]
based on the branch sidmanifold water.stl file

**Comment by petebachant** [comment]
Maybe you need to refine near those edges and surfaces more in `snappyHexMeshDict` or refine the background mesh a little.

**Comment by sidnigam** [comment]
i tried changing the refinement to 4 4 level for it, and doing searchable cylinders and searchable box, but no luck

**Comment by petebachant** [comment]
Hmm, is the point in mesh in `snappyHexMeshDict` actually set to be inside the geometry?

**Comment by sidnigam** [comment]
yeah, i think the problem is when snappy is running, it moves some points - 

Calculating patchDisplacement as distance to nearest surface point ...
Wanted displacement : average:0.00042282558 min:1.8461472e-05 max:0.0010438124
Calculated surface displacement in = 0 s

Detecting near surfaces ...
Overriding nearest with intersection of close gaps at 0 out of 4650 points.
Overriding displacement on features :
   implicit features    : false
   explicit features    : true
   multi-patch features : true

Detected 0 baffle edges out of 9144 edges.
Initially selected 129 points out of 4650 for reverse attraction.
Selected 377 points out of 4650 for reverse attraction.
Removing constraints near multi-patch points : changed 0 points
Stringing feature edges : changed 8 points
Stringing feature edges : changed 0 points

**Comment by sidnigam** [comment]
Figured it out! :dancer: :smile:

**Comment by petebachant** [comment]
:fireworks:
