### ISSUE TITLE
Create different STL for each patch

### ISSUE THREAD

**Issue by petebachant** [pbnh/unh-aquaponics#6]
It looks like this may be easier than using `topoSet` and `createPatch`: http://www.cfd-online.com/Forums/openfoam-meshing-utilities/61510-how-create-patch-after-snappyhexmesh.html

In SolidWorks, export each surface as a different STL, i.e., inlet, outlet, and walls. Note there are other free tools out there that may make it easier to do this in a single step (and on Linux), e.g., Salome, FreeCAD, MeshLab.

**Comment by sidnigam** [comment]
Done :) check workingMesh branch to see
